name: Deploy to cPanel

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Code 🚚
        uses: actions/checkout@v3

      - name: Install Dependencies 📦
        run: npm install -f

    #   - name: create env file
    #     run: |
    #       touch .env
    #       echo VITE_API_BASE=${{ vars.API_BASE_PRODUCTION }} >> .env 

      - name: Build vite app 🏗️
        run: npm run build

      - name: Move .htaccess file to /dist directory
        run: mv .htaccess dist/

      - name: Upload to cPanel 📂
        uses: SamKirkland/FTP-Deploy-Action@v4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dangerous-clean-slate: true
          # timeout: 300000
          local-dir: ./dist/